# Generated by Django 6.0.7 on 2026-07-17 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagenservicio', models.ImageField(blank=True, null=True, upload_to='servicios/')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=500)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200, unique=True)),
                ('clave', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200, unique=True)),
                ('telefono', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Formato de teléfono inválido')])),
                ('direccion', models.CharField(max_length=200)),
                ('primer_login', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField()),
                ('estado_matricula', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='pendiente', max_length=30)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('textoblog', models.TextField()),
                ('imagenblog', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('fecha_publicacion', models.DateField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='core.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='core.usuario')),
            ],
        ),
    ]
