# Generated by Django 6.0.7 on 2026-07-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_rol_rol_rol_nombre_alter_rol_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='primer_login',
        ),
    ]
